version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 5252864Mi
      MYSQL_DATABASE: library_db